name: ML Algorithms Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'pre-commit-ci-update-config'
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}-py${{ matrix.PYTHON_VERSION }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        PYTHON_VERSION: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install
        shell: bash
        run: |
          pip install --upgrade -e ".[dev,sklearn]"

      - name: Run tests
        run: |
          pytest hyperspy_ml_algorithms/tests/ -v --tb=short --cov=hyperspy_ml_algorithms --cov-report=xml

      - uses: codecov/codecov-action@v3

      - name: Lint
        run: |
          pip install ruff
          ruff check hyperspy_ml_algorithms/
          ruff format --check hyperspy_ml_algorithms/
